-- Source registry: checked public feeds, no content or private data.
insert into public.sources(id,name,url,feed_url,kind,enabled) values
 ('human-in-the-loop','Human in the Loop · Andreas Horn','https://www.humanintheloop.online/','https://www.humanintheloop.online/feed','discovery',false),
 ('aidrops','AiDrops','https://www.aidrop.news/',null,'discovery',false),
 ('ai-breakfast','AI Breakfast','https://aibreakfast.beehiiv.com/',null,'discovery',false),
 ('rundown','The Rundown AI','https://www.therundown.ai/',null,'discovery',false),
 ('neuron','The Neuron','https://www.theneuron.ai/',null,'discovery',false),
 ('tldr','TLDR AI','https://tldr.tech/ai',null,'discovery',false),
 ('bens-bites','Ben’s Bites','https://www.bensbites.com/','https://www.bensbites.com/feed','discovery',true),
 ('superhuman','Superhuman AI','https://www.superhuman.ai/',null,'discovery',false),
 ('openai','OpenAI','https://openai.com/news/','https://openai.com/news/rss.xml','primary',true),
 ('anthropic','Anthropic','https://www.anthropic.com/news',null,'primary',false),
 ('google-ai','Google AI','https://blog.google/technology/ai/','https://blog.google/innovation-and-ai/technology/ai/rss/','primary',true),
 ('deepmind','Google DeepMind','https://deepmind.google/blog/','https://deepmind.google/blog/rss.xml','primary',true),
 ('meta','Meta AI','https://ai.meta.com/blog/',null,'primary',false),
 ('microsoft','Microsoft AI','https://blogs.microsoft.com/ai/','https://blogs.microsoft.com/ai/feed/','primary',false),
 ('nvidia','NVIDIA','https://blogs.nvidia.com/','https://blogs.nvidia.com/feed/','primary',true),
 ('mistral','Mistral AI','https://mistral.ai/news','https://mistral.ai/news/rss','primary',true),
 ('xai','xAI','https://x.ai/news',null,'primary',false),
 ('perplexity','Perplexity','https://www.perplexity.ai/hub',null,'primary',false),
 ('techcrunch','TechCrunch AI','https://techcrunch.com/category/artificial-intelligence/','https://techcrunch.com/category/artificial-intelligence/feed/','press',true),
 ('venturebeat','VentureBeat AI','https://venturebeat.com/category/ai/','https://venturebeat.com/category/ai/feed/','press',false),
 ('mit-review','MIT Technology Review','https://www.technologyreview.com/topic/artificial-intelligence/','https://www.technologyreview.com/feed/','press',true),
 ('ars-technica','Ars Technica','https://arstechnica.com/','https://feeds.arstechnica.com/arstechnica/index','press',true),
 ('wired','WIRED','https://www.wired.com/tag/artificial-intelligence/','https://www.wired.com/feed/tag/ai/latest/rss','press',true),
 ('the-batch','The Batch · DeepLearning.AI','https://www.deeplearning.ai/the-batch/','https://www.deeplearning.ai/the-batch/feed/','analysis',false),
 ('one-useful-thing','One Useful Thing · Ethan Mollick','https://www.oneusefulthing.org/','https://www.oneusefulthing.org/feed','analysis',true),
 ('import-ai','Import AI · Jack Clark','https://importai.substack.com/','https://importai.substack.com/feed','analysis',true),
 ('latent-space','Latent Space','https://www.latent.space/','https://www.latent.space/feed','analysis',true),
 ('interconnects','Interconnects · Nathan Lambert','https://www.interconnects.ai/','https://www.interconnects.ai/feed','analysis',true),
 ('ahead-of-ai','Ahead of AI · Sebastian Raschka','https://magazine.sebastianraschka.com/','https://magazine.sebastianraschka.com/feed','analysis',true),
 ('last-week-in-ai','Last Week in AI','https://lastweekin.ai/','https://lastweekin.ai/feed','analysis',true),
 ('ai-snake-oil','AI Snake Oil','https://www.aisnakeoil.com/','https://www.normaltech.ai/feed','analysis',true)
on conflict(id) do update set name=excluded.name,url=excluded.url,feed_url=excluded.feed_url,kind=excluded.kind,enabled=excluded.enabled;
