import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('PostgreSQL: isolamento, pagamentos, cotas e idempotência',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
 await db.exec(`create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to anon,authenticated;grant select,insert,update,delete on storage.objects to authenticated;`);
 for(const name of (await readdir(new URL('../supabase/migrations/',import.meta.url))).sort()){let sql=await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8');sql=sql.replace('create extension if not exists pgcrypto;','');await db.exec(sql);}
 const u1='11111111-1111-4111-8111-111111111111',u2='22222222-2222-4222-8222-222222222222';
 await db.exec(`insert into auth.users values('${u1}'),('${u2}');insert into profiles(user_id,company,sector,size,goals,email_opt_in) values('${u1}','Empresa Um','Retail','2–10','Melhorar o atendimento',true),('${u2}','Empresa Dois','Retail','2–10','Organizar a operação',false);insert into subscriptions(user_id,status) values('${u1}','active'),('${u2}','inactive');insert into editions(user_id,week_start) values('${u1}','2026-09-07'),('${u2}','2026-09-07');`);
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${u1}',false);`);
 assert.equal((await db.query('select * from profiles')).rows.length,1);
 assert.equal((await db.query('select id from editions')).rows.length,1);
 await assert.rejects(db.exec(`update subscriptions set status='active' where user_id='${u2}'`));
 await assert.rejects(db.exec(`select delivery_payload from editions`));
 await assert.rejects(db.exec(`select reserve_ai_call()`));
 assert.equal((await db.query(`update profiles set company='Invadida' where user_id='${u2}' returning user_id`)).rows.length,0);
 await db.exec('reset role;set role anon;');await assert.rejects(db.exec('select * from profiles'));await assert.rejects(db.exec('select id from editions'));await db.exec('reset role;');
 assert.equal((await db.query<{ok:boolean}>(`select acquire_job('daily','${u1}') as ok`)).rows[0].ok,true);
 assert.equal((await db.query<{ok:boolean}>(`select acquire_job('daily','${u2}') as ok`)).rows[0].ok,false);
 await db.exec(`select release_job('daily','${u2}')`);assert.equal((await db.query('select * from job_locks')).rows.length,1);
 await db.exec(`select release_job('daily','${u1}')`);assert.equal((await db.query('select * from job_locks')).rows.length,0);
 for(let i=0;i<10;i++)assert.equal((await db.query<{ok:boolean}>('select reserve_ai_call() as ok')).rows[0].ok,true);assert.equal((await db.query<{ok:boolean}>('select reserve_ai_call() as ok')).rows[0].ok,false);
 await db.exec(`select enqueue_editions('2026-09-14');select enqueue_editions('2026-09-14');`);assert.equal((await db.query("select * from editions where week_start='2026-09-14'")).rows.length,1);
 await db.exec(`insert into partner_applications values('${u1}','Parceiro','Especialista em automação para empresas','https://example.com','contato@example.com',null,null,null,array['Retail'],array['automation'],'strategic',now());`);
 const order=await db.query<{id:string}>(`insert into orders(user_id,product,value_cents) values('${u1}','strategic',1000) returning id`);const id=order.rows[0].id;
 await db.exec(`select confirm_payment('${id}','pay_1','sub_1',now()+interval '1 month');select confirm_payment('${id}','pay_1','sub_1',now()+interval '2 months');`);
 assert.equal((await db.query('select * from payments')).rows.length,1);const partner=(await db.query<{active:boolean;plan:string}>('select * from partners')).rows[0];assert.equal(partner.active,true);assert.equal(partner.plan,'strategic');
 await db.exec(`insert into partner_showcases(user_id,items) values('${u1}','[]');set role anon;`);
 assert.equal((await db.query('select * from partner_showcases')).rows.length,1);
 await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${u2}',false);`);
 await assert.rejects(db.exec(`update partner_showcases set items='[]' where user_id='${u1}'`));
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('partner-media','${u1}/0')`));
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('partner-media','${u2}/0')`));
 await db.exec(`select set_config('request.jwt.claim.sub','${u1}',false);insert into storage.objects(bucket_id,name) values('partner-media','${u1}/0');`);
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('partner-media','${u1}/6')`));
 await assert.rejects(db.exec(`update storage.objects set name='${u2}/0' where name='${u1}/0'`));
 await db.exec(`select set_config('request.jwt.claim.sub','${u2}',false);`);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await db.exec(`reset role;select revoke_payment('pay_1');set role anon;`);
 assert.equal((await db.query('select * from partner_showcases')).rows.length,0);
 await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${u1}',false);`);
 assert.equal((await db.query('select * from partner_showcases')).rows.length,1);
 await db.exec('reset role;');assert.equal((await db.query<{active:boolean}>('select active from partners')).rows[0].active,false);
 await db.exec(`insert into sources(id,name,url,kind) values('vendor','Fornecedor','https://example.com','primary'),('press','Jornal','https://news.example.com','press');`);
 await assert.rejects(db.exec(`insert into articles(source_id,source_name,source_url,title,title_key,excerpt,published_at,status,human_angle,perspective_attribution,perspective_evidence) values('vendor','Fornecedor','https://example.com/a','Título original','key-vendor','Texto original',now(),'published','Uma perspectiva longa o suficiente para a verificação.','Fornecedor','Um trecho suficientemente longo usado como evidência.')`));
 await assert.rejects(db.exec(`insert into articles(source_id,source_name,source_url,title,title_key,excerpt,published_at,status) values('press','Jornal','https://news.example.com/a','Título original','key-press','Texto original',now(),'published')`));
 await db.close();
});
