"use client";
import {useActionState} from 'react';
import {saveRoadmap} from '@/app/roadmap-actions';
import {sectors} from '@/lib/types';
import {label} from '@/lib/labels';
import {roadmapChoices,roadmapArrayFields} from '@/lib/roadmap-options';
export function RoadmapForm({initial={}}:{initial?:Record<string,unknown>}){
 const [state,action,pending]=useActionState(saveRoadmap,{message:''});
 const details=(initial.details||{}) as Record<string,unknown>;
 const text=(name:string,title:string,min:number,max:number,placeholder:string)=> <label className="field full">{title}<textarea name={name} required={min>0} minLength={min} maxLength={max} placeholder={placeholder} defaultValue={String(name.startsWith('details.')?details[name.slice(8)]||'':initial[name]||'')}/></label>;
 const choice=(name:keyof typeof roadmapChoices,title:string)=>roadmapArrayFields.some(key=>key===name)?<fieldset className="field full"><legend>{title}</legend><p>{name==='opportunity_focus'?'Escolha de uma a três prioridades.':'Selecione todas as opções que descrevem sua realidade.'}</p>{roadmapChoices[name].map(value=><label key={value} style={{display:'flex',gap:10,alignItems:'center',marginBottom:8}}><input type="checkbox" name={`details.${name}`} value={value} defaultChecked={Array.isArray(details[name])&&(details[name] as string[]).includes(value)} style={{width:'auto'}}/>{value}</label>)}</fieldset>:<label className="field">{title}<select required name={`details.${name}`} defaultValue={String(details[name]||'')}><option value="" disabled>Selecione uma opção</option>{roadmapChoices[name].map(value=><option key={value}>{value}</option>)}</select></label>;
 const section=(number:number,title:string,description:string,children:React.ReactNode)=><section style={{borderTop:'1px solid #d9d6ce',padding:'28px 0'}}><p className="eyebrow">Etapa {number} de 6</p><h3>{title}</h3><p>{description}</p><div className="form-grid">{children}</div></section>;
 return <form action={action}><input type="hidden" name="questionnaire_version" value="2"/><p>Reserve cerca de 15 minutos. Descreva um processo concreto. Se não souber quantas horas ele consome, deixe esse valor em branco. Evite incluir dados pessoais de clientes.</p>
 {section(1,'Sua empresa','Vamos dimensionar os projetos para o tamanho e o setor do negócio.',<><label className="field">Nome da empresa<input name="company" required minLength={2} maxLength={120} defaultValue={String(initial.company||'')}/></label><label className="field">Setor<select name="sector" defaultValue={String(initial.sector||'Other')}>{sectors.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>{text('team','Quantas pessoas trabalham na empresa e quais são as principais funções?',1,100,'Ex.: 8 pessoas, com 3 em vendas e 2 no atendimento.')}</>)}
 {section(2,'Modelo de negócio','Entender o que vocês entregam e como geram receita ajuda a identificar oportunidades relevantes.',<>{text('offer','Qual é o principal produto ou serviço?',15,1200,'Descreva o que vende, como entrega e o que diferencia sua empresa.')}{text('customer','Quem é o principal cliente?',3,300,'Perfil do cliente, necessidades e como ele chega até vocês.')}{choice('revenue_model','Como a empresa gera receita?')}</>)}
 {section(3,'Funcionamento operacional','Mapeie o trabalho repetido, as ferramentas e a dependência de pessoas.',<>{choice('recurring_tasks','Quais atividades se repetem na operação?')}{choice('person_dependency','Quais áreas dependem de pessoas específicas?')}{text('systems','Quais sistemas e ferramentas sustentam a operação?',3,600,'Nomes das ferramentas, planilhas e como as informações passam entre elas.')}{text('bottleneck','Descreva o processo que mais consome tempo, do início ao fim.',20,1500,'O que inicia o processo? Quem faz cada etapa? Onde há retrabalho?')}{choice('process_owner','Quem executa esse processo?')}<label className="field">Horas gastas por semana, somando todas as pessoas (opcional)<input name="hours" type="number" min={0} max={1000} step="0.5" placeholder="Deixe em branco se não souber" defaultValue={initial.hours===null||initial.hours===undefined?'':Number(initial.hours)}/></label></>)}
 {section(4,'Fricções e gargalos','Diferencie as causas dos problemas dos sintomas percebidos pela equipe.',<>{choice('error_areas','Onde erros e inconsistências aparecem?')}{choice('decision_delays','O que atrasa as decisões?')}{choice('available_data','Quais informações já existem e poderiam ser melhor aproveitadas?')}</>)}
 {section(5,'Objetivo estratégico','Explore o que a empresa pode passar a fazer com IA e defina as prioridades.',<>{choice('opportunity_focus','Que tipos de oportunidade você quer explorar?')}{text('details.new_capability','O que sua empresa gostaria de conseguir fazer, mas hoje não consegue?',15,1000,'Pense em novas ofertas, mercados, análises ou formas de atender. Descreva o que impede isso hoje.')}{text('details.decision_challenge','Que decisão importante é difícil de tomar hoje?',10,800,'Que informações faltam? Como a decisão é tomada? Se não houver uma dificuldade, informe isso.')}{text('details.customer_opportunity','Onde o cliente se beneficiaria de uma experiência mais personalizada?',10,800,'Pense na descoberta, compra, uso ou pós-venda. Se não souber, informe isso.')}{text('details.knowledge_gap','Que trabalho depende de conhecimento especializado, análise ou criatividade que a equipe tem dificuldade de acessar?',10,800,'Ex.: analisar contratos, preparar propostas ou aprender sobre um novo mercado.')}{text('goal','Qual resultado deve melhorar primeiro?',10,1000,'Ex.: reduzir o tempo de resposta às propostas sem perder qualidade.')}{text('details.success_baseline','Como isso funciona hoje e como vocês saberão que melhorou?',10,600,'Ex.: hoje uma proposta leva dois dias; vamos acompanhar prazo e correções. Se não mede ainda, diga isso.')}{choice('budget','Qual orçamento mensal pode sustentar o projeto?')}{choice('deadline','Quando vocês pretendem começar?')}</>)}
 {section(6,'Maturidade em IA','A recomendação precisa caber na capacidade da equipe e respeitar as restrições do negócio.',<>{choice('ai_usage','Como vocês usam IA ou automação hoje?')}{text('details.ai_tools','Quais ferramentas já usam e em quais atividades? (opcional)',0,600,'Ex.: ChatGPT para rascunhos, com revisão da equipe.')}{choice('team_readiness','Como a equipe costuma adotar novas ferramentas?')}{choice('implementation_limits','Quais limites precisam ser considerados?')}{text('constraints','Há outras restrições ou cuidados importantes? (opcional)',0,1000,'Ex.: dados confidenciais, aprovação do gestor ou sistema sem integração.')}</>)}
 <button className="button" disabled={pending}>{pending?'Salvando…':'Salvar meu diagnóstico ↗'}</button><p className="form-message" role="status">{state.message}</p></form>;
}
