import type {Article,Partner,Edition} from './types';
export const demoArticles:Article[]=[
{id:'demo-1',title:'Sua equipe já usa IA. A empresa sabe como?',summary:'O funcionário encontra um jeito de terminar a tarefa mais rápido. A empresa descobre depois. Esta pauta de exemplo olha para o uso informal de IA no trabalho e para a conversa que gestores precisam ter com suas equipes.',source_name:'Pauta ilustrativa · Trabalho',source_url:'https://www.oneusefulthing.org/',published_at:'2026-09-09T09:00:00Z',category:'Work',sectors:['Professional services','Real estate'],human_angle:'A pergunta útil para a liderança é onde a equipe precisa de orientação, tempo para testar e critérios claros de revisão.',perspective_attribution:'Exemplo editorial Ventura'},
{id:'demo-2',title:'Quando um alerta sobre IA vira a conversa da semana',summary:'Previsões alarmantes chamam atenção, especialmente quando vêm de alguém que trabalhou nos grandes laboratórios. Esta pauta de exemplo propõe conferir quem falou, em qual contexto e com quais evidências antes de tirar conclusões.',source_name:'Pauta ilustrativa · Debate',source_url:'https://www.technologyreview.com/topic/artificial-intelligence/',published_at:'2026-09-09T08:00:00Z',category:'Backstage',sectors:['Other','Professional services'],human_angle:'Uma declaração pode abrir um debate importante. O prazo de uma previsão continua sendo uma hipótese, mesmo quando seu autor conhece o setor.',perspective_attribution:'Exemplo editorial Ventura'},
{id:'demo-3',title:'O cliente quer ser atendido. Ele se importa se é por uma IA?',summary:'Rapidez ajuda, mas uma resposta automática que não resolve pode gerar mais trabalho. Esta pauta de exemplo acompanha a tensão entre automatizar o atendimento e preservar a confiança de quem precisa de ajuda.',source_name:'Pauta ilustrativa · Negócios',source_url:'https://techcrunch.com/category/artificial-intelligence/',published_at:'2026-09-08T09:00:00Z',category:'Business',sectors:['Retail','Hospitality','Real estate'],human_angle:'Olhar para resolução, reclamações e acesso a uma pessoa traz mais contexto do que contar apenas quantas mensagens foram automatizadas.',perspective_attribution:'Exemplo editorial Ventura'},
{id:'demo-4',title:'A disputa por talentos também revela o rumo da IA',summary:'Mudanças de equipe, saídas de executivos e novas empresas podem dizer muito sobre as prioridades dos laboratórios. Esta pauta de exemplo mostra como acompanhar esses bastidores sem confundir versões dos envolvidos com fatos confirmados.',source_name:'Pauta ilustrativa · Bastidores',source_url:'https://www.wired.com/tag/artificial-intelligence/',published_at:'2026-09-08T08:00:00Z',category:'Backstage',sectors:['Other','Professional services'],human_angle:'As escolhas de quem constrói a tecnologia ajudam a entender o mercado. Motivos atribuídos a uma saída exigem fontes e contexto.',perspective_attribution:'Exemplo editorial Ventura'}];
export const demoPartners:Partner[]=[
{id:'demo-p1',media:[{path:'/partner-demo/automacao-1.svg',url:'/partner-demo/automacao-1.svg',kind:'image',caption:'Rotinas mais simples'},{path:'/partner-demo/automacao-2.svg',url:'/partner-demo/automacao-2.svg',kind:'image',caption:'Integre seus processos'}],slug:'exemplo-automacao',name:'Estúdio de automação',description:'Perfil de exemplo para automação de processos, integração de sistemas e assistentes internos.',sectors:['Real estate','Construction','Professional services'],capabilities:['automation','sales'],website:'',email:null,phone:null,linkedin:null,instagram:null,placement:'newsletter',plan:'strategic',active:true},
{id:'demo-p2',media:[{path:'/partner-demo/marketing-1.svg',url:'/partner-demo/marketing-1.svg',kind:'image',caption:'Conteúdo com propósito'},{path:'/partner-demo/marketing-2.svg',url:'/partner-demo/marketing-2.svg',kind:'image',caption:'Acompanhe os resultados'}],slug:'exemplo-marketing',name:'Especialista em marketing',description:'Perfil de exemplo para uma equipe que ajuda empresas a organizar a produção de conteúdo e os relatórios de campanhas.',sectors:['Retail','Hospitality'],capabilities:['marketing','analytics'],website:'',email:null,phone:null,linkedin:null,instagram:null,placement:'directory',plan:'catalog',active:true},
{id:'demo-p3',media:[{path:'/partner-demo/treinamento-1.svg',url:'/partner-demo/treinamento-1.svg',kind:'image',caption:'Sua equipe com autonomia'},{path:'/partner-demo/treinamento-2.svg',url:'/partner-demo/treinamento-2.svg',kind:'image',caption:'Aprender colocando em prática'}],slug:'exemplo-treinamento',name:'Parceiro de treinamento',description:'Perfil de exemplo para oficinas práticas e capacitação de equipes no uso de IA.',sectors:['Education','Professional services'],capabilities:['training'],website:'',email:null,phone:null,linkedin:null,instagram:null,placement:'directory',plan:'catalog',active:true}];
export const demoEdition:Edition={id:'demo-edition',week_start:'2026-09-07',status:'demo',sent_at:null,articles:demoArticles,partners:[demoPartners[0]],content:{headline:'Seu próximo teste: responder contatos com mais agilidade',overview:[{article_id:'demo-1',takeaway:'Converse com a equipe sobre o uso real de IA antes de escolher a próxima ferramenta.'},{article_id:'demo-3',takeaway:'Avalie se a automação resolve a necessidade do cliente e mantém uma saída para atendimento humano.'}],relevant:[{article_id:'demo-1',why:'Para uma imobiliária, preparar a primeira resposta a um contato é uma tarefa com escopo claro. Acompanhe o tempo de resposta e a precisão antes de ampliar o teste.'}],actions:[{title:'Escolha um tipo de dúvida recorrente',detail:'Separe 10 exemplos sem dados pessoais e escreva as respostas que sua equipe aprovaria.',effort:'30 minutos',capability:'sales'},{title:'Compare os rascunhos com o processo atual',detail:'Revise cada resposta. Registre erros factuais e o tempo necessário para chegar a uma mensagem aprovada.',effort:'1 hora',capability:'automation'}]}};
